sudo: false
language: ruby
rvm:
  - 2.6.3
services:
  - postgresql
before_install:
  - gem install bundler:1.17.3
before_script:
  - cd spec/etl_app
  - rails db:create
  - rails db:migrate
  - cd ../../