sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.3
services:
  - postgresql
before_install:
  - gem install bundler -v 1.17.3
before_script:
  - bundle install
  - cd spec/etl_app
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - cd ../../