sudo: false
script:
  - "bundle exec rake neo4j:install['community-2.2.0-M02'] neo4j:start default --trace"
language: ruby
rvm:
  - 2.6.3
services:
  - postgresql
before_install:
  - gem install bundler:1.17.3
before_script:
  - cd spec/etl_app
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - cd ../../